;                     PERSISTENCE OF VISION RAY TRACER
;
;                           POV-Ray VERSION 3.0
;
;                         SAMPLE .povrayrc FILE
;
;  This file contains options which control how POV-Ray does its job.
;  The file should be placed in your home directory as .povrayrc, and
;  it will automaticaly read when POVRAY is run.
;
;  The general form of the options is "Variable=value".  Everything 
;  between the equals sign and the end of the line is considered part 
;  of the value.  The spacing and layout is free-form but only one option 
;  per line is allowed.  Variables and values are not case-sensitive.  
;
;  Note: characters after a semi-colon are treated as a comment, unless
;        the semi-colon is immediately preceded by a backslash like \;
;
;  Traditional POV-Ray switches beginning with + or - are also allowed
;  and they may be given with more than one switch per line.  
;
Display_Gamma = 1.0
Test_Abort = off
Pause_when_Done = off
Output_File_Type = p
Library_Path = /opt/group/lib/povray3
Warning_Console = off

Antialias = on
